### ISSUE TITLE
Action doesn't create or set value to env vars

### ISSUE THREAD

**Issue by marcosrmartin** [JJ/pull-request-checks-action#262]
This is the workflow:
![image](https://user-images.githubusercontent.com/75510647/228374907-8e64d3e8-79f3-400c-86b4-428448fcd730.png)

Next, the template with the "AVANZAR" option checked
![image](https://user-images.githubusercontent.com/75510647/228376025-99d529b0-189f-4761-9312-5572d88ad7f2.png)

Finally, its result:
![image](https://user-images.githubusercontent.com/75510647/228376122-be2aa21b-5a26-42cd-9d2f-0b74fbae7bbe.png)

**Comment by JJ** [comment]
Thanks for the report; I'll check it out.

**Comment by JJ** [comment]
So you think this is due to the list format?
